# Generated by Django 4.2.5 on 2023-09-28 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResumeScreeningApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_name', models.CharField(max_length=100)),
                ('password', models.TextField()),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='login',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
