# Generated by Django 4.2.5 on 2023-09-28 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ResumeScreeningApp', '0002_resumeprofile_alter_login_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resumeprofile',
            old_name='password',
            new_name='profile_keyword',
        ),
    ]
