# Generated by Django 4.2.5 on 2023-10-01 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResumeScreeningApp', '0003_rename_password_resumeprofile_profile_keyword'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_name', models.CharField(max_length=100)),
                ('can_email', models.CharField(max_length=100)),
                ('can_contact', models.CharField(max_length=15)),
                ('can_skills', models.TextField()),
                ('active', models.BooleanField()),
                ('created_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100)),
                ('active', models.BooleanField()),
            ],
        ),
    ]
