# Generated by Django 4.2.5 on 2023-10-02 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResumeScreeningApp', '0004_candidateprofile_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='can_status',
            field=models.FloatField(default=0.0),
        ),
    ]
